// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="nco_nco,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.331000,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=128,HLS_SYN_LUT=181,HLS_VERSION=2022_2}" *)

module nco (
        ap_clk,
        ap_rst_n,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt,
        s_axi_DATA_AWVALID,
        s_axi_DATA_AWREADY,
        s_axi_DATA_AWADDR,
        s_axi_DATA_WVALID,
        s_axi_DATA_WREADY,
        s_axi_DATA_WDATA,
        s_axi_DATA_WSTRB,
        s_axi_DATA_ARVALID,
        s_axi_DATA_ARREADY,
        s_axi_DATA_ARADDR,
        s_axi_DATA_RVALID,
        s_axi_DATA_RREADY,
        s_axi_DATA_RDATA,
        s_axi_DATA_RRESP,
        s_axi_DATA_BVALID,
        s_axi_DATA_BREADY,
        s_axi_DATA_BRESP
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_DATA_DATA_WIDTH = 32;
parameter    C_S_AXI_DATA_ADDR_WIDTH = 6;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_DATA_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;
input   s_axi_DATA_AWVALID;
output   s_axi_DATA_AWREADY;
input  [C_S_AXI_DATA_ADDR_WIDTH - 1:0] s_axi_DATA_AWADDR;
input   s_axi_DATA_WVALID;
output   s_axi_DATA_WREADY;
input  [C_S_AXI_DATA_DATA_WIDTH - 1:0] s_axi_DATA_WDATA;
input  [C_S_AXI_DATA_WSTRB_WIDTH - 1:0] s_axi_DATA_WSTRB;
input   s_axi_DATA_ARVALID;
output   s_axi_DATA_ARREADY;
input  [C_S_AXI_DATA_ADDR_WIDTH - 1:0] s_axi_DATA_ARADDR;
output   s_axi_DATA_RVALID;
input   s_axi_DATA_RREADY;
output  [C_S_AXI_DATA_DATA_WIDTH - 1:0] s_axi_DATA_RDATA;
output  [1:0] s_axi_DATA_RRESP;
output   s_axi_DATA_BVALID;
input   s_axi_DATA_BREADY;
output  [1:0] s_axi_DATA_BRESP;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg    sine_sample_ap_vld;
wire   [15:0] step_size;
reg   [15:0] temp_V;
wire   [11:0] sine_lut_V_address0;
reg    sine_lut_V_ce0;
wire   [15:0] sine_lut_V_q0;
wire   [63:0] zext_ln436_fu_99_p1;
wire   [15:0] add_ln813_fu_77_p2;
wire    ap_CS_fsm_state2;
wire   [11:0] address_V_fu_89_p4;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 temp_V = 16'd0;
end

nco_sine_lut_V_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
sine_lut_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(sine_lut_V_address0),
    .ce0(sine_lut_V_ce0),
    .q0(sine_lut_V_q0)
);

nco_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

nco_DATA_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_DATA_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_DATA_DATA_WIDTH ))
DATA_s_axi_U(
    .AWVALID(s_axi_DATA_AWVALID),
    .AWREADY(s_axi_DATA_AWREADY),
    .AWADDR(s_axi_DATA_AWADDR),
    .WVALID(s_axi_DATA_WVALID),
    .WREADY(s_axi_DATA_WREADY),
    .WDATA(s_axi_DATA_WDATA),
    .WSTRB(s_axi_DATA_WSTRB),
    .ARVALID(s_axi_DATA_ARVALID),
    .ARREADY(s_axi_DATA_ARREADY),
    .ARADDR(s_axi_DATA_ARADDR),
    .RVALID(s_axi_DATA_RVALID),
    .RREADY(s_axi_DATA_RREADY),
    .RDATA(s_axi_DATA_RDATA),
    .RRESP(s_axi_DATA_RRESP),
    .BVALID(s_axi_DATA_BVALID),
    .BREADY(s_axi_DATA_BREADY),
    .BRESP(s_axi_DATA_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .sine_sample(sine_lut_V_q0),
    .sine_sample_ap_vld(sine_sample_ap_vld),
    .step_size(step_size)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        temp_V <= add_ln813_fu_77_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        sine_lut_V_ce0 = 1'b1;
    end else begin
        sine_lut_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        sine_sample_ap_vld = 1'b1;
    end else begin
        sine_sample_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln813_fu_77_p2 = (temp_V + step_size);

assign address_V_fu_89_p4 = {{add_ln813_fu_77_p2[15:4]}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign sine_lut_V_address0 = zext_ln436_fu_99_p1;

assign zext_ln436_fu_99_p1 = address_V_fu_89_p4;

endmodule //nco
